//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NetChess.rc
//
#define IDC_BUTTON_VIEW_LIST            2
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_NETCHETYPE                  129
#define IDR_MAINFRAME_EXTENDED          129
#define IDD_DIALOG_OPTIONS              131
#define IDB_BITMAP_BASE                 132
#define IDB_BITMAP_ROOK_WHITE           133
#define IDB_BITMAP_BISHOP_WHITE         134
#define IDB_BITMAP_KING_BLACK           135
#define IDB_BITMAP_KING_WHITE           136
#define IDB_BITMAP_KNIGHT_BLACK         137
#define IDB_BITMAP_KNIGHT_WHITE         138
#define IDB_BITMAP_PAWN_BLACK           139
#define IDB_BITMAP_PAWN_WHITE           140
#define IDB_BITMAP_QUEEN_BLACK          141
#define IDB_BITMAP_QUEEN_WHITE          142
#define IDB_BITMAP_ROOK_BLACK           143
#define IDB_BITMAP_BISHOP_BLACK         144
#define IDD_DIALOG_SERVER_INFO          145
#define IDD_DIALOG_MESSAGE              146
#define IDD_DIALOG_HISTORY              147
#define IDD_DIALOG_PICK_PIECE           148
#define IDI_ICON_MAINFRAME_OPPOSITE     149
#define IDR_SHELL_MENU                  150
#define IDD_DIALOG_PROPERTIES           177
#define IDD_DIALOG_ACCEPT               178
#define IDD_DIALOG_LOST_PIECE           179
#define IDD_DIALOG_DEMO_FEED            180
#define IDD_DIALOG_HOWTOPLAY            182
#define IDD_DIALOG_DEMO_INTERVAL        185
#define IDD_DIALOG_PGN_DATA             186
#define IDD_DIALOG_DEMO_GOTO            187
#define IDD_DIALOG_GOTO_PGN_GAME        188
#define IDD_DIALOG_GAME_INFO            189
#define IDD_DIALOG_OBSERVERS            192
#define IDD_DIALOG_CONVERT              193
#define IDD_DIALOG_COMMENT              194
#define IDB_BITMAP_BASE2                197
#define IDI_ICON1                       199
#define IDB_BITMAP_BASE3                200
#define IDD_DIALOG_IMAGE                201
#define IDD_DIALOG_ENGINE_LOG           202
#define IDD_DIALOG_NETCHESS_LOG         203
#define IDD_DIALOG_ENGINE_CONFIGURE     204
#define IDD_DIALOG_UCI_OPTIONS          205
#define IDD_DIALOG_GAME_STATE           206
#define IDD_DIALOG_ENGINE_LEVEL         207
#define IDD_DIALOG_ENTER_MOVE           208
#define IDD_DIALOG_ICS_CONFIGURE        209
#define IDD_DIALOG_ICS_WINDOWS          210
#define IDD_DIALOG_ICS_PLAYERS_LIST     212
#define IDD_DIALOG_SEEK_LIST            213
#define IDD_DIALOG_TIME_CONTROL         214
#define IDD_DIALOG_ICS_CHAT             215
#define IDB_BITMAP_BASE4                216
#define IDD_DIALOG_MESSAGE_ICS          216
#define IDD_DIALOG_MAIL_TO              217
#define IDD_DIALOG_MAIL_FROM            218
#define IDC_CHECK_WHITE_ON_TOP          1000
#define IDC_BUTTON_WHITE_COLOR          1001
#define IDC_BUTTON_BLACK_COLOR          1002
#define IDC_STATIC_WHITE                1003
#define IDC_STATIC_BLACK                1004
#define IDC_BUTTON_WHITE_COLOR2         1005
#define IDC_BUTTON_BLACK_COLOR2         1006
#define IDC_EDIT_PORT_NUMBER            1007
#define IDC_STATIC_WHITE2               1007
#define IDC_IPADDRESS                   1008
#define IDC_STATIC_BLACK2               1008
#define IDC_EDIT_MESSAGE                1009
#define IDC_EDIT_RECEIVE_MESSAGE        1010
#define IDC_EDIT_HISTORY                1011
#define IDC_STATIC_ROOT_WHITE           1013
#define IDC_STATIC_BITMAP_KNIGHT        1014
#define IDC_STATIC_BISHOP_WHITE         1015
#define IDC_STATIC_QUEEN_WHITE          1016
#define IDC_STATIC_KING_WHITE           1017
#define IDC_STATIC_PAWN_WHITE           1018
#define IDC_STATIC_ROOT_BLACK           1019
#define IDC_STATIC_KNIGHT_BLACK         1020
#define IDC_STATIC_BISHOP_BLACK         1021
#define IDC_STATIC_QUEEN_BLACK          1022
#define IDC_STATIC_KING_BLACK           1023
#define IDC_STATIC_PAWN_BLACK           1024
#define IDC_STATIC_STATUS               1025
#define IDC_STATIC_IP_ADDRESS           1026
#define IDC_STATIC_CLIENT_STATUS        1026
#define IDC_STATIC_EMPTY                1027
#define IDC_STATIC_PIECE_TYPE1          1028
#define IDC_STATIC_PIECE_TYPE2          1029
#define IDC_STATIC_PIECE_TYPE3          1030
#define IDC_RADIO_WHITE                 1032
#define IDC_RADIO_BLACK                 1033
#define IDC_STATIC_ACCEPT               1037
#define IDC_STATIC_W1                   1038
#define IDC_STATIC_W2                   1039
#define IDC_STATIC_W3                   1040
#define IDC_STATIC_W4                   1041
#define IDC_STATIC_W5                   1042
#define IDC_STATIC_W6                   1043
#define IDC_STATIC_W7                   1044
#define IDC_STATIC_W8                   1045
#define IDC_STATIC_W9                   1046
#define IDC_STATIC_W10                  1047
#define IDC_STATIC_W11                  1048
#define IDC_STATIC_W12                  1049
#define IDC_STATIC_W13                  1050
#define IDC_STATIC_W14                  1051
#define IDC_STATIC_W15                  1052
#define IDC_STATIC_W16                  1053
#define IDC_STATIC_B1                   1054
#define IDC_STATIC_B2                   1055
#define IDC_STATIC_B3                   1056
#define IDC_STATIC_B4                   1057
#define IDC_STATIC_B5                   1058
#define IDC_STATIC_B6                   1059
#define IDC_STATIC_B7                   1060
#define IDC_STATIC_B8                   1061
#define IDC_STATIC_B9                   1062
#define IDC_STATIC_B10                  1063
#define IDC_STATIC_B11                  1064
#define IDC_STATIC_B12                  1065
#define IDC_STATIC_B13                  1066
#define IDC_STATIC_B14                  1067
#define IDC_STATIC_B15                  1068
#define IDC_STATIC_B16                  1069
#define IDC_COMBO_FROM_LETTER           1076
#define IDC_COMBO_FROM_NUMBER           1077
#define IDC_COMBO_TO_LETTER             1078
#define IDC_COMBO_TO_NUMBER             1079
#define IDC_BUTTON_ADD                  1083
#define IDC_RADIO_TOSS                  1084
#define IDC_EDIT_HOWTOPLAY              1087
#define IDC_EDIT_NAME                   1088
#define IDC_EDIT_DEMO_INTERVAL          1089
#define IDC_EDIT_PGN_DATA               1091
#define IDC_BUTTON_OPEN                 1092
#define IDC_LIST_HISTORY                1094
#define IDC_BUTTON_FIRST                1096
#define IDC_BUTTON_PREV                 1097
#define IDC_BUTTON_NEXT                 1098
#define IDC_BUTTON_LAST                 1099
#define IDC_STATIC_GAME_NUMBER          1100
#define IDC_EDIT_GAME_NUMBER            1101
#define IDC_BUTTON_GO                   1103
#define IDC_EDIT_EVENT                  1104
#define IDC_EDIT_SITE                   1105
#define IDC_EDIT_DATE                   1106
#define IDC_EDIT_ROUND                  1107
#define IDC_EDIT_WHITE                  1108
#define IDC_EDIT_BLACK                  1109
#define IDC_EDIT_RESULT                 1110
#define IDC_LIST_OBSERVERS              1111
#define IDC_RADIO_PGN                   1112
#define IDC_RADIO_FEN                   1113
#define IDC_RADIO_EPD                   1114
#define IDC_EDIT_FILENAME               1115
#define IDC_BUTTON_BROWSE               1118
#define IDC_EDIT_COMMENT                1119
#define IDC_CHECK_AUTO_SAVE             1123
#define IDC_CHECK_SAVE_WITH_HISTORY     1124
#define IDC_BUTTON_SELECT_IMAGE         1128
#define IDC_STATIC_IMAGE                1129
#define IDC_EDIT_FENSTRING              1130
#define IDC_EDIT_INTERVAL               1131
#define IDC_EDIT_ENGINE_LOG             1132
#define IDC_BUTTON_APPLY_SAVE           1133
#define IDC_EDIT_ENGINE_COMMAND         1134
#define IDC_BUTTON_SEND                 1136
#define IDC_BUTTON_CLEAR                1137
#define IDC_EDIT_NETCHESS_LOG           1138
#define IDC_BUTTON_SAVE                 1138
#define IDC_CHECK_NETCHESS_LOG          1139
#define IDC_CHECK_PGN_MAIL_FORMAT       1140
#define IDC_RADIO_WBI                   1142
#define IDC_RADIO_WBII                  1143
#define IDC_RADIO_UCII                  1144
#define IDC_RADIO_UCIII                 1145
#define IDC_EDIT_WHITEELO               1146
#define IDC_EDIT_BLACKELO               1147
#define IDC_EDIT_ECO                    1148
#define IDC_EDIT_PLAYCOUNT              1149
#define IDC_EDIT_EVENT_DATE             1150
#define IDC_EDIT_READ_OPTIONS           1151
#define IDC_LIST_SET_OPTIONS            1153
#define IDC_EDIT_SET_OPTIONS            1154
#define IDC_RADIO_FEN_STRING            1156
#define IDC_RADIO_STARTPOS              1157
#define IDC_BUTTON_COPY                 1159
#define IDC_CHECK_WHITE_KING            1160
#define IDC_CHECK_WHITE_ROOK_A          1161
#define IDC_CHECK_BLACK_KING            1162
#define IDC_CHECK_BLACK_ROOK_A          1163
#define IDC_CHECK_WHITE_ROOT_H          1164
#define IDC_CHECK_BLACK_ROOK_H          1165
#define IDC_CHECK_WHITE_O_O_O           1168
#define IDC_CHECK_WHITE_O_O             1169
#define IDC_CHECK_BLACK_O_O_O           1170
#define IDC_CHECK_BLACK_O_O             1171
#define IDC_EDIT_MOVESTIMECONTROL       1173
#define IDC_EDIT_TIME_CONTROL           1174
#define IDC_EDIT_CONV_CLOCK_MODE        1175
#define IDC_EDIT_DEF_WHITE_ENGINE       1176
#define IDC_BUTTON_WHITE_BROWSE         1177
#define IDC_EDIT_DEF_BLACK_ENGINE       1178
#define IDC_BUTTON_BLACK_BROWSE         1179
#define IDC_EDIT_FONT                   1181
#define IDC_EDIT_FONT_SIZE              1182
#define IDC_FONT                        1183
#define IDC_RADIO_DEFAULT               1184
#define IDC_RADIO_FONT_BOARD            1186
#define IDC_EDIT_MOVE                   1187
#define IDC_EDIT1                       1189
#define IDC_EDIT_COMMAND                1189
#define IDC_EDIT_ICS_LIST               1189
#define IDC_EDIT_WB_NUMBER_OF_MOVES     1189
#define IDC_EDIT_MAIL_SERVER            1189
#define IDC_EDIT2                       1191
#define IDC_EDIT_ICS_LOG                1191
#define IDC_EDIT_WB_TIME                1191
#define IDC_EDIT_FROM                   1191
#define IDC_EDIT_USER_NAME              1192
#define IDC_EDIT_PASSWORD               1193
#define IDC_BUTTON_CONNECT              1194
#define IDC_COMBO_ICS_SERVER_NAME       1196
#define IDC_BUTTON_SEEK                 1198
#define IDC_BUTTON_ABORT                1199
#define IDC_BUTTON_PLAY                 1200
#define IDC_BUTTON_QUIT                 1201
#define IDC_EDIT_PLAY                   1202
#define IDC_BUTTON_DRAW                 1203
#define IDC_BUTTON_RESIGN               1204
#define IDC_BUTTON_PLAYERS              1205
#define IDC_BUTTON_WHO                  1206
#define IDC_BUTTON_GAMES                1207
#define IDC_BUTTON_SHOUT_0              1208
#define IDC_BUTTON_SHOUT_1              1209
#define IDC_BUTTON_SOUGHT               1210
#define IDC_BUTTON_VIEW                 1211
#define IDC_BUTTON_HELP                 1212
#define IDC_BUTTON_STYLE12              1213
#define IDC_EDIT_PLAY_TYPE              1214
#define IDC_BUTTON_ACCEPT               1215
#define IDC_STATIC_LIST                 1224
#define IDC_LIST_SEEK_LIST              1225
#define IDC_CHECK_EXPAND_MOVE           1228
#define IDC_RADIO_CONVENTIONAL_CLOCK    1232
#define IDC_RADIO_INCREAMENTAL_CLOCK    1233
#define IDC_RADIO_EXACT_NUMBER          1234
#define IDC_EDIT_WB_BASE_TIME           1235
#define IDC_EDIT_WB_INC_TIME            1236
#define IDC_EDIT_WB_EXACT_SECONDS       1237
#define IDC_EDIT_UCI_WTIME              1238
#define IDC_EDIT_UCI_BTIME              1239
#define IDC_EDIT_UCI_WINC               1240
#define IDC_EDIT_UCI_BINC               1241
#define IDC_EDIT_UCI_MOVETIME           1242
#define IDC_CHECK_INFINITE              1243
#define IDC_STATIC_MYNAME               1244
#define IDC_BUTTON_DISCONNECT           1245
#define IDC_EDIT_USER_MESSAGE           1249
#define IDC_STATIC_GROUP                1251
#define IDC_RADIO_WHITEENGINE_WBI       1255
#define IDC_RADIO_WHITEENGINE_WBII      1256
#define IDC_RADIO_WHITEENGINE_UCII      1257
#define IDC_RADIO_WHITEENGINE_UCIII     1258
#define IDC_EDIT_TO                     1261
#define IDC_RADIO_BLACKENGINE_WBI       1263
#define IDC_EDIT_PORT                   1263
#define IDC_RADIO_BLACKENGINE_WBII      1264
#define IDC_RADIO_BLACKENGINE_UCII      1265
#define IDC_RADIO_BLACKENGINE_UCIII     1266
#define IDC_RICHEDIT_RECEIVE_MESSAGE    1267
#define IDC_CHECK_EXTENDED_VIEW         1268
#define IDC_CHECK_SAVE_LAST_GAME        1269
#define IDC_CHECK_BLACK_ENGINE_AUTO_START 1270
#define ID_VIEW_HIDE                    32771
#define ID_EDIT_OPTIONS                 32772
#define ID_TOOLS_CLIENT                 32773
#define ID_TOOLS_SERVER                 32774
#define ID_TOOLS_SENDMESSAGE            32775
#define ID_TOOLS_HISTORY                32778
#define ID_VIEW_NUMBER                  32779
#define ID_VIEW_LETTER                  32780
#define ID_FILE_SAVEHISTORY             32781
#define ID_TOOLS_PLAYHISTORY            32782
#define ID_SHELL_CLOSE                  32783
#define ID_SHELL_VIEW                   32784
#define ID_VIEW_HISTORY                 32786
#define ID_TOOLS_WHITEONTOP             32787
#define ID_EDIT_MOVEFIRST               32792
#define ID_EDIT_MOVELAST                32793
#define ID_HELP_HOWTOPLAY               32799
#define ID_TOOLS_DISCONNECT             32800
#define ID_EDIT_PROPERTIES              32801
#define D_EDIT_PROPERTIES               32802
#define ID_TOOLS_RESIGN                 32804
#define ID_TOOLS_DRAW                   32805
#define ID_VIEW_LOSTPIECES              32806
#define ID_FILE_FEED                    32807
#define ID_TOOLS_LEARN                  32808
#define ID_EDIT_SETBOARD                32809
#define ID_EDIT_CHECKMOVE               32811
#define ID_EDIT_MANUALEDIT_EMPTY        32813
#define ID_EDIT_MANUALEDIT_START        32814
#define ID_EDIT_MANUALEDIT_END          32815
#define ID_EDIT_MANUALEDIT_PLAYERTURN   32816
#define ID_VIEW_DEMO                    32818
#define ID_FILE_SUBMITPGNDATA           32819
#define ID_VIEW_DEMO_START              32821
#define ID_VIEW_DEMO_STOP               32822
#define ID_VIEW_DEMO_PAUSE              32823
#define ID_VIEW_DEMO_GOTO               32824
#define ID_FILE_OPENPGNFILE             32825
#define ID_FILE_LOADFIRSTGAME           32826
#define ID_FILE_LOADNEXTGAME            32827
#define ID_FILE_RELOADTHEPGNGAME        32828
#define ID_FILE_GOTOPGNGAME             32829
#define ID_FILE_LOADPREVPGNGAME         32830
#define ID_EDIT_GAMEINFO                32831
#define ID_VIEW_FLIPBOARD               32832
#define ID_EDIT_MANUALEDIT_PAUSECLOCK   32833
#define ID_FILE_SAVEBOARD               32834
#define ID_VIEW_OBSERVERSLIST           32835
#define ID_FILE_CONVERT                 32836
#define ID_EDIT_COMMENT                 32837
#define ID_EDIT_PREFERENCES             32838
#define ID_VIEW_EXTEND                  32839
#define ID_FILE_LOADLASTGAME            32842
#define ID_EDIT_COPYFEN                 32843
#define ID_EDIT_COPYEPD                 32844
#define ID_VIEW_IMAGE                   32847
#define ID_EDIT_COPYFENPOSITION         32849
#define ID_EDIT_COPYEPDPOSITION         32850
#define ID_TOOLS_ENGINE                 32851
#define ID_TOOLS_BLACKENGINE            32853
#define ID_TOOLS_WHITEENGINE_LOAD       32854
#define ID_TOOLS_WHITEENGINE_START      32855
#define ID_TOOLS_WHITEENGINE_STOP       32856
#define ID_TOOLS_WHITEENGINE_CLOSE      32857
#define ID_TOOLS_BLACKENGINE_LOAD       32858
#define ID_TOOLS_BLACKENGINE_START      32859
#define ID_TOOLS_BLACKENGINE_STOP       32860
#define ID_TOOLS_BLACKENGINE_CLOSE      32861
#define ID_TOOLS_WHITEENGINE_CONFIGURE  32862
#define ID_TOOLS_BLACKENGINE_CONFIGURE  32863
#define ID_TOOLS_WHITEENGINE_LOG        32864
#define ID_TOOLS_BLACKENGINE_LOG        32865
#define ID_TOOLS_WHITEENGINE_MOVENOW    32866
#define ID_TOOLS_BLACKENGINE_MOVENOW    32867
#define ID_TOOLS_WHITEENGINE            32868
#define ID_TOOLS_WHITEENGINESETTINGS_WHITEASENGINE 32870
#define ID_TOOLS_BLACKENGINESETTINGS_BLACKASENGINE 32871
#define ID_VIEW_LOG                     32872
#define ID_VIEW_KNIGHTSTOUR             32873
#define ID_TOOLS_WHITEENGINESETTINGS_PONDON 32875
#define ID_TOOLS_BLACKENGINESETTINGS_PONDOR 32876
#define ID_TOOLS_WHITEENGINESETTINGS_PONDOR 32877
#define ID_HELP_CONTENTSANDINDEX        32878
#define ID_VIEW_GAME1                   32879
#define ID_VIEW_GAME2                   32880
#define ID_VIEW_GAME3                   32881
#define ID_VIEW_GAME4                   32882
#define ID_VIEW_GAME5                   32883
#define ID_FILE_NEWGAME                 32884
#define ID_TOOLS_WHITEENGINE_CONFIGURECHESSENGINE 32890
#define ID_TOOLS_WHITEENGINE_SETTINGS   32899
#define ID_TOOLS_WHITEENGINE_SETTINGS_WHITEASENGINE 32901
#define ID_TOOLS_BLACKENGINE_SETTINGS_BLACKASENGINE 32902
#define ID_EDIT_GAMESTATE               32904
#define ID_WHITEENGINE_PONDER           32905
#define ID_BLACKENGINE_PONDOR           32906
#define ID_EDIT_LEVELS                  32907
#define ID_WHITEENGINE_ANALYZE          32908
#define ID_BLACKENGINE_ANALYZE          32909
#define ID_WHITEENGINE_DEFAULT          32910
#define ID_BLACKENGINE_DEFAULT          32911
#define ID_WHITEENGINE_RELOAD           32912
#define ID_BLACKENGINE_RELOAD           32913
#define ID_TOOLS_AREYOUOK               32914
#define ID_VIEW_LEARNING                32915
#define ID_VIEW_EXTENDEDVIEW            32916
#define ID_EDIT_ENTERMOVE               32917
#define ID_ICS_CONFIGURE                32918
#define ID_ICS_WINDOW                   32919
#define ID_HELP_HTTPWWWGEOCITIESCOMRAOAVM 32920
#define ID_ICS_PLAYERS                  32921
#define ID_ICS_GAMES                    32922
#define ID_ICS_WHO                      32923
#define ID_ICS_SOUGHT                   32924
#define ID_ICS_SEEKLIST                 32925
#define ID_WHITEENGINE_SETBOARD         32926
#define ID_BLACKENGINE_SETBOARD         32927
#define ID_WHITEENGINE_ONLYANALYZE      32928
#define ID_BLACKENGINE_ONLYANALYZE      32929
#define ID_EDIT_TIMECONTROL             32931
#define ID_ICS_CHAT                     32932
#define ID_TOOLS_MAILTO                 32933
#define ID_TOOLS_MAILFROM               32934
#define ID_REPLAY_REPLAYALL             32937

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         32938
#define _APS_NEXT_CONTROL_VALUE         1271
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
